### ISSUE TITLE
Update references to User.name field

### ISSUE THREAD

**Issue by anncatton** [overture-stack/ego-ui#105]
The `name` field is being removed in Ego 4.0.0, any references to it in the ui need to be replaced:
- ItemSelector menu for associated users
- ChildUserDisplayName in list of associated users for an entity (grid view only)

Agreed to display:

- Ego user.id, FirstName+LastName

Specific UI areas:

- Policies/Applications control to add users
- Grid control that shows more when having > 5 users

**Comment by b-f-chan** [comment]
Tested successfully in QA --> Controls to add users in EGO UI (policies, applications, all lists/grids) are correctly showing First Name and Last Name instead of just Name or E-mail now.
