### ISSUE TITLE
Fix Handling for Display Names in EGO Admin UI

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego-ui#125]
**Problem:**

- Providers may not necessarily enforce a user's names to be entered on their profile
- E.g. GITHUB captures the user's name in their profile as a single string/text Name field
- If the user only has a single contiguous string in the GITHUB name field (e.g. "Brandon"), EGO seems unable to interpret or parse it correctly
- This results in 2 issues in EGO Admin UI:
    - (1) The user account name fields are blank - The user essentially has no name, which does not make sense, every user will have a name.
    - (2) Because the UI has validation that requires the name fields to be mandatory, but these fields are not allowed to be edited, the Admin can never update the user's profile.  For example, if the Admin tries to change the user's role to an Admin, they cannot save the update since the UI is expecting the names to be populated first.
- Note that, if the user updates their GITHUB name to have exactly 2 strings separated by a space (e.g. "Brandon Chan"), then EGO UI updates correctly.  Exactly 2 is required, if 3 strings are entered separated by a space, then the same error occurs.
- The EGO DB however does not enforce the name fields (First Name, Last Name) as mandatory, this is only in the UI

**Agreed Solution:**

EGO-UI changes:

- Make First Name, Last Name editable again in the UI
- Display info in the Name field using this cascading logic:
    - Show concatenated names first if available,
    - Else show e-mail,
    - Else show EGO user UUID
    
EGO core changes (to be done in ticket #):

- Set First Name, Last Name from the provider token only on initial user create; do not update on subsequent logins
- Update name parsing logic as follows:
    - Split string by whitespace
    - Put last element as Last Name
    - Everything else goes into First Name

~~**Potential Solution:**~~

- ~~To be discussed with team before proceeding~~
- ~~First investigate how the GITHUB SSO filter is interpreting the names and fix if necessary~~
- ~~We should enforce at least one name (e.g. First Name) as mandatory in the DB and UI; there is no human user that does not have a name, so this is a reasonable restriction~~
- ~~For simplicity, if we only parse one value/string, we can put it in First Name as default~~
- ~~Additionally, we should add error handling to tell the user their login failed if there is no Name, and gracefully return them to the login page (not just a generic 403 error)~~

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/4535bba8-52e3-4313-981f-88b7ab1ed871)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/c34ce54d-4545-4f89-8ed5-e90206212a12)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/e2ee6484-21e7-4fec-bc40-d0dc7882a32e)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/9598c4f6-ab8b-4919-a400-ea75f4c47bd4)

**Comment by anncatton** [comment]
Will be adding a fix to integrate the update user endpoint changing from a `PUT` to a `PATCH` in [ego-561](https://github.com/overture-stack/ego/issues/561)

**Comment by b-f-chan** [comment]
Tested multiple naming scenarios for each provider in staging

All tests passed (results recorded in team drive, contact me if you need access to the document)
