### ISSUE TITLE
Adjusting Table Columns Causes Them to Misalign

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/ego-ui#143]
Adjusting any of the table columns in Ego-UI causes the columns to misalign and display improperly

Example:
![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/0c2b0577-4dca-49e8-83e6-3663d004a2db)

**Comment by anncatton** [comment]
I think this is a duplicate of #96

**Comment by rosibaj** [comment]
Closing as a duplicate.
