### ISSUE TITLE
Disabled user can access Admin Portal , gets 403 errors

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/ego-ui#18]
Steps to execute:

1. Disable Ego user 
2. Log back into Admin portal (without refreshing browser)
3. User can log in , but Ego api calls return 403 error

Expected behaviour : User should see message that they are not able to access the admin portal.

**Comment by alekspejovic** [comment]
![Screen Shot 2019-03-06 at 10.58.33 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beaeda44f12fd00123cac0e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454f56b7191a379ef0c2e59415c4dbc30254d58eeb9cb74fce36f34985619e8806c0b27c53542feb1d31abf09ba21834a8cbfeedf19c5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee0455dac133e66e570316e0a.png)

**Comment by andricDu** [comment]
Merged.
