### ISSUE TITLE
Fix EGO UI repository warnings

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego-ui#36]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/8d9e4824-e8db-4f95-93d1-15b4247eb82b)

**Comment by d8660091** [comment]
https://github.com/overture-stack/ego-ui/pull/21

**Comment by rosibaj** [comment]
Tested - warnings are nolonger visible in repo.  Thanks for the fix @d8660091 !!
