### ISSUE TITLE
Deleting new permission while still in edit does not unstage the change

### ISSUE THREAD

**Issue by anncatton** [overture-stack/ego-ui#73]
In dev environment

Steps to reproduce:
1. navigate to policies tab and select a policy
2. Click edit
3. Add either a group or user permission and select a permission level.
4. Click the `x` to delete that new item from the list
5. Click `Save`
6. The new permission is created and the network tab shows a 404 where the delete request failed because that permission did not exist yet.

Expected behaviour:
The new permission should be reverted from staged changes and should not be created.

**Comment by rosibaj** [comment]
tested and no seeing the issue on argo-qa any longer.  lgtm thanks @anncatton !
