### ISSUE TITLE
BUG - Ego UI not displaying unauthorized when user is disabled. 

### ISSUE THREAD

**Issue by andricDu** [overture-stack/ego-ui#87]
## Description
Reported by @henro001 
His user was disabled but was an admin user. When logging into the Ego Admin UI it just took him back to login pages.

## Expected Behaviour
Should display message that user is unauthorized or disabled. 

## Actual Behaviour
Goes back to login page. 

## Possible Fix
Handle rejection correctly. 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by anncatton** [comment]
Closing as duplicate, can do work in #130
